[package]
name = "pyro"
version = "0.1.0"
description = "Lightweight, dedicated server software for Minecraft: Bedrock Edition"
edition = "2021"
authors = ["Ruben Adema"]
repository = "https://github.com/teampathfinders/pyro"
license = "Apache-2.0"
rust-version = "1.68.0"

[lib]
name = "pyro"
path = "src/lib.rs"

[features]
# Requires the tokio_unstable rustc flag
tokio-console = ["console-subscriber"]

[dependencies]
ext = { package = "pyro-extensions", path = "../ext" }
nbt = { package = "pyro-nbt", path = "../nbt" }
util = { package = "pyro-util", path = "../util" }
level = { package = "pyro-level", path = "../level" }

console-subscriber = { version = "0.1.9", optional = true }
tokio = { version = "1.31.0", features = ["net", "rt-multi-thread", "macros", "time", "sync", "signal"] }
tokio-util = "0.7.8"
tracing = "0.1.38"
tracing-subscriber = { version = "0.3.17", features = ["ansi", "fmt", "json", "smallvec", "parking_lot"], default-features = false }
rand = "0.8.5"
dashmap = "5.4.0"
parking_lot = "0.12.1"
lazy_static = "1.4.0"
flate2 = "1.0.26"
async-recursion = "1.0.2"
jsonwebtoken = "8.3.0"
serde = { version = "1.0.164", default-features = false }
serde_json = "1.0.104"
base64 = "0.21.2"
p384 = { version = "0.13.0", features = ["std", "ecdh", "ecdsa", "pem"], default-features = false }
sha2 = { version = "0.10.7", default-features = false }
ctr = "0.9.2"
aes = "0.8.3"
serde_repr = "0.1.11"
uuid = { version = "1.4.0", features = ["serde"], default-features = false }
clap = { version = "4.3.10", features = ["cargo", "std"], default-features = false }
anyhow = { version = "1.0.71", features = ["backtrace"] }
lru = "0.10.1"
bytemuck = "1.13.1"
