[package]
name = "pyro-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
better_any = { version = "0.2.0", features = ["derive"] }
tokio = { version = "1.26.0", features = ["macros", "rt", "rt-multi-thread"] }
