[package]
name = "pyro-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
better_any = { version = "0.2.0", features = ["derive"] }
dashmap = "5.4.0"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
tokio = { version = "1.26.0", features = ["macros", "rt", "rt-multi-thread", "time"] }
