name: CI / Clippy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  rust-clippy-analyze:
    name: clippy-analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clippy
        run: rustup toolchain install 1.75.0 --profile minimal -c clippy

      - name: Dependency cache
        uses: Swatinem/rust-cache@v2.2.1

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Run clippy
        run:
          RUSTFLAGS="--cfg skip_leveldb" 
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true