name: CI / Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: "sccache"
  CARGO_INCREMENTAL: 0

concurrency:
  group: ci-${{ github.ref }}

jobs:
  run-tests:
    name: 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
  
    steps:
    - name: Install Rust
      run: rustup toolchain install 1.75.0 --profile minimal
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
      
    - name: Run tests
      run: cargo +1.72.0 test
